/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SignRequestData struct for SignRequestData
type SignRequestData struct {
	Mode SignMode `json:"mode"`
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _SignRequestData SignRequestData

// NewSignRequestData instantiates a new SignRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignRequestData(mode SignMode, message string, ) *SignRequestData {
	this := SignRequestData{}
	this.Mode = mode
	this.Message = message
	return &this
}

// NewSignRequestDataWithDefaults instantiates a new SignRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignRequestDataWithDefaults() *SignRequestData {
	this := SignRequestData{}
	return &this
}

// GetMode returns the Mode field value
func (o *SignRequestData) GetMode() SignMode {
	if o == nil  {
		var ret SignMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *SignRequestData) GetModeOk() (*SignMode, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *SignRequestData) SetMode(v SignMode) {
	o.Mode = v
}

// GetMessage returns the Message field value
func (o *SignRequestData) GetMessage() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SignRequestData) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SignRequestData) SetMessage(v string) {
	o.Message = v
}

func (o SignRequestData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mode"] = o.Mode
	}
	if true {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SignRequestData) UnmarshalJSON(bytes []byte) (err error) {
	varSignRequestData := _SignRequestData{}

	if err = json.Unmarshal(bytes, &varSignRequestData); err == nil {
		*o = SignRequestData(varSignRequestData)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "mode")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSignRequestData struct {
	value *SignRequestData
	isSet bool
}

func (v NullableSignRequestData) Get() *SignRequestData {
	return v.value
}

func (v *NullableSignRequestData) Set(val *SignRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableSignRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableSignRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignRequestData(val *SignRequestData) *NullableSignRequestData {
	return &NullableSignRequestData{value: val, isSet: true}
}

func (v NullableSignRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


