/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SystemState the model 'SystemState'
type SystemState string

// List of SystemState
const (
	UNPROVISIONED SystemState = "Unprovisioned"
	LOCKED SystemState = "Locked"
	OPERATIONAL SystemState = "Operational"
)

func (v *SystemState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SystemState(value)
	for _, existing := range []SystemState{ "Unprovisioned", "Locked", "Operational",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SystemState", value)
}

// Ptr returns reference to SystemState value
func (v SystemState) Ptr() *SystemState {
	return &v
}

type NullableSystemState struct {
	value *SystemState
	isSet bool
}

func (v NullableSystemState) Get() *SystemState {
	return v.value
}

func (v *NullableSystemState) Set(val *SystemState) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemState) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemState(val *SystemState) *NullableSystemState {
	return &NullableSystemState{value: val, isSet: true}
}

func (v NullableSystemState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

