/*
 * NitroHSM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PublicKey struct for PublicKey
type PublicKey struct {
	Purpose KeyPurpose `json:"purpose"`
	Algorithm KeyAlgorithm `json:"algorithm"`
	Key PublicKeyKey `json:"key"`
	Operations int32 `json:"operations"`
}

// NewPublicKey instantiates a new PublicKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicKey(purpose KeyPurpose, algorithm KeyAlgorithm, key PublicKeyKey, operations int32, ) *PublicKey {
	this := PublicKey{}
	this.Purpose = purpose
	this.Algorithm = algorithm
	this.Key = key
	this.Operations = operations
	return &this
}

// NewPublicKeyWithDefaults instantiates a new PublicKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicKeyWithDefaults() *PublicKey {
	this := PublicKey{}
	return &this
}

// GetPurpose returns the Purpose field value
func (o *PublicKey) GetPurpose() KeyPurpose {
	if o == nil  {
		var ret KeyPurpose
		return ret
	}

	return o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetPurposeOk() (*KeyPurpose, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Purpose, true
}

// SetPurpose sets field value
func (o *PublicKey) SetPurpose(v KeyPurpose) {
	o.Purpose = v
}

// GetAlgorithm returns the Algorithm field value
func (o *PublicKey) GetAlgorithm() KeyAlgorithm {
	if o == nil  {
		var ret KeyAlgorithm
		return ret
	}

	return o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetAlgorithmOk() (*KeyAlgorithm, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Algorithm, true
}

// SetAlgorithm sets field value
func (o *PublicKey) SetAlgorithm(v KeyAlgorithm) {
	o.Algorithm = v
}

// GetKey returns the Key field value
func (o *PublicKey) GetKey() PublicKeyKey {
	if o == nil  {
		var ret PublicKeyKey
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetKeyOk() (*PublicKeyKey, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PublicKey) SetKey(v PublicKeyKey) {
	o.Key = v
}

// GetOperations returns the Operations field value
func (o *PublicKey) GetOperations() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetOperationsOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Operations, true
}

// SetOperations sets field value
func (o *PublicKey) SetOperations(v int32) {
	o.Operations = v
}

func (o PublicKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["purpose"] = o.Purpose
	}
	if true {
		toSerialize["algorithm"] = o.Algorithm
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["operations"] = o.Operations
	}
	return json.Marshal(toSerialize)
}

type NullablePublicKey struct {
	value *PublicKey
	isSet bool
}

func (v NullablePublicKey) Get() *PublicKey {
	return v.value
}

func (v *NullablePublicKey) Set(val *PublicKey) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKey) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKey(val *PublicKey) *NullablePublicKey {
	return &NullablePublicKey{value: val, isSet: true}
}

func (v NullablePublicKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


