/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SystemUpdateData struct for SystemUpdateData
type SystemUpdateData struct {
	ReleaseNotes string `json:"releaseNotes"`
	AdditionalProperties map[string]interface{}
}

type _SystemUpdateData SystemUpdateData

// NewSystemUpdateData instantiates a new SystemUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemUpdateData(releaseNotes string, ) *SystemUpdateData {
	this := SystemUpdateData{}
	this.ReleaseNotes = releaseNotes
	return &this
}

// NewSystemUpdateDataWithDefaults instantiates a new SystemUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemUpdateDataWithDefaults() *SystemUpdateData {
	this := SystemUpdateData{}
	return &this
}

// GetReleaseNotes returns the ReleaseNotes field value
func (o *SystemUpdateData) GetReleaseNotes() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ReleaseNotes
}

// GetReleaseNotesOk returns a tuple with the ReleaseNotes field value
// and a boolean to check if the value has been set.
func (o *SystemUpdateData) GetReleaseNotesOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReleaseNotes, true
}

// SetReleaseNotes sets field value
func (o *SystemUpdateData) SetReleaseNotes(v string) {
	o.ReleaseNotes = v
}

func (o SystemUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["releaseNotes"] = o.ReleaseNotes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SystemUpdateData) UnmarshalJSON(bytes []byte) (err error) {
	varSystemUpdateData := _SystemUpdateData{}

	if err = json.Unmarshal(bytes, &varSystemUpdateData); err == nil {
		*o = SystemUpdateData(varSystemUpdateData)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "releaseNotes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemUpdateData struct {
	value *SystemUpdateData
	isSet bool
}

func (v NullableSystemUpdateData) Get() *SystemUpdateData {
	return v.value
}

func (v *NullableSystemUpdateData) Set(val *SystemUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemUpdateData(val *SystemUpdateData) *NullableSystemUpdateData {
	return &NullableSystemUpdateData{value: val, isSet: true}
}

func (v NullableSystemUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


