/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UnattendedBootConfig struct for UnattendedBootConfig
type UnattendedBootConfig struct {
	Status string `json:"status"`
}

// NewUnattendedBootConfig instantiates a new UnattendedBootConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnattendedBootConfig(status string, ) *UnattendedBootConfig {
	this := UnattendedBootConfig{}
	this.Status = status
	return &this
}

// NewUnattendedBootConfigWithDefaults instantiates a new UnattendedBootConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnattendedBootConfigWithDefaults() *UnattendedBootConfig {
	this := UnattendedBootConfig{}
	return &this
}

// GetStatus returns the Status field value
func (o *UnattendedBootConfig) GetStatus() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnattendedBootConfig) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnattendedBootConfig) SetStatus(v string) {
	o.Status = v
}

func (o UnattendedBootConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableUnattendedBootConfig struct {
	value *UnattendedBootConfig
	isSet bool
}

func (v NullableUnattendedBootConfig) Get() *UnattendedBootConfig {
	return v.value
}

func (v *NullableUnattendedBootConfig) Set(val *UnattendedBootConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUnattendedBootConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUnattendedBootConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnattendedBootConfig(val *UnattendedBootConfig) *NullableUnattendedBootConfig {
	return &NullableUnattendedBootConfig{value: val, isSet: true}
}

func (v NullableUnattendedBootConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnattendedBootConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


