/*
 * NitroHSM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject struct for InlineObject
type InlineObject struct {
	UnlockPassphrase string `json:"unlockPassphrase"`
	AdminPassphrase string `json:"adminPassphrase"`
	SystemTime string `json:"systemTime"`
}

// NewInlineObject instantiates a new InlineObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject(unlockPassphrase string, adminPassphrase string, systemTime string, ) *InlineObject {
	this := InlineObject{}
	this.UnlockPassphrase = unlockPassphrase
	this.AdminPassphrase = adminPassphrase
	this.SystemTime = systemTime
	return &this
}

// NewInlineObjectWithDefaults instantiates a new InlineObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObjectWithDefaults() *InlineObject {
	this := InlineObject{}
	return &this
}

// GetUnlockPassphrase returns the UnlockPassphrase field value
func (o *InlineObject) GetUnlockPassphrase() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.UnlockPassphrase
}

// GetUnlockPassphraseOk returns a tuple with the UnlockPassphrase field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetUnlockPassphraseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnlockPassphrase, true
}

// SetUnlockPassphrase sets field value
func (o *InlineObject) SetUnlockPassphrase(v string) {
	o.UnlockPassphrase = v
}

// GetAdminPassphrase returns the AdminPassphrase field value
func (o *InlineObject) GetAdminPassphrase() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AdminPassphrase
}

// GetAdminPassphraseOk returns a tuple with the AdminPassphrase field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetAdminPassphraseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AdminPassphrase, true
}

// SetAdminPassphrase sets field value
func (o *InlineObject) SetAdminPassphrase(v string) {
	o.AdminPassphrase = v
}

// GetSystemTime returns the SystemTime field value
func (o *InlineObject) GetSystemTime() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.SystemTime
}

// GetSystemTimeOk returns a tuple with the SystemTime field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetSystemTimeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SystemTime, true
}

// SetSystemTime sets field value
func (o *InlineObject) SetSystemTime(v string) {
	o.SystemTime = v
}

func (o InlineObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["unlockPassphrase"] = o.UnlockPassphrase
	}
	if true {
		toSerialize["adminPassphrase"] = o.AdminPassphrase
	}
	if true {
		toSerialize["systemTime"] = o.SystemTime
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject struct {
	value *InlineObject
	isSet bool
}

func (v NullableInlineObject) Get() *InlineObject {
	return v.value
}

func (v *NullableInlineObject) Set(val *InlineObject) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject(val *InlineObject) *NullableInlineObject {
	return &NullableInlineObject{value: val, isSet: true}
}

func (v NullableInlineObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


