/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PrivateKey struct for PrivateKey
type PrivateKey struct {
	Mechanisms []KeyMechanism `json:"mechanisms"`
	Algorithm KeyAlgorithm `json:"algorithm"`
	Key KeyPrivateData `json:"key"`
}

// NewPrivateKey instantiates a new PrivateKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateKey(mechanisms []KeyMechanism, algorithm KeyAlgorithm, key KeyPrivateData, ) *PrivateKey {
	this := PrivateKey{}
	this.Mechanisms = mechanisms
	this.Algorithm = algorithm
	this.Key = key
	return &this
}

// NewPrivateKeyWithDefaults instantiates a new PrivateKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateKeyWithDefaults() *PrivateKey {
	this := PrivateKey{}
	return &this
}

// GetMechanisms returns the Mechanisms field value
func (o *PrivateKey) GetMechanisms() []KeyMechanism {
	if o == nil  {
		var ret []KeyMechanism
		return ret
	}

	return o.Mechanisms
}

// GetMechanismsOk returns a tuple with the Mechanisms field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetMechanismsOk() (*[]KeyMechanism, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Mechanisms, true
}

// SetMechanisms sets field value
func (o *PrivateKey) SetMechanisms(v []KeyMechanism) {
	o.Mechanisms = v
}

// GetAlgorithm returns the Algorithm field value
func (o *PrivateKey) GetAlgorithm() KeyAlgorithm {
	if o == nil  {
		var ret KeyAlgorithm
		return ret
	}

	return o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetAlgorithmOk() (*KeyAlgorithm, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Algorithm, true
}

// SetAlgorithm sets field value
func (o *PrivateKey) SetAlgorithm(v KeyAlgorithm) {
	o.Algorithm = v
}

// GetKey returns the Key field value
func (o *PrivateKey) GetKey() KeyPrivateData {
	if o == nil  {
		var ret KeyPrivateData
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetKeyOk() (*KeyPrivateData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PrivateKey) SetKey(v KeyPrivateData) {
	o.Key = v
}

func (o PrivateKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mechanisms"] = o.Mechanisms
	}
	if true {
		toSerialize["algorithm"] = o.Algorithm
	}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullablePrivateKey struct {
	value *PrivateKey
	isSet bool
}

func (v NullablePrivateKey) Get() *PrivateKey {
	return v.value
}

func (v *NullablePrivateKey) Set(val *PrivateKey) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateKey) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateKey(val *PrivateKey) *NullablePrivateKey {
	return &NullablePrivateKey{value: val, isSet: true}
}

func (v NullablePrivateKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


