/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
}

impl ToString for LogLevel {
    fn to_string(&self) -> String {
        match self {
            Self::Debug => String::from("debug"),
            Self::Info => String::from("info"),
            Self::Warning => String::from("warning"),
            Self::Error => String::from("error"),
        }
    }
}

impl Default for LogLevel {
    fn default() -> LogLevel {
        Self::Debug
    }
}
