/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkConfig {
    #[serde(rename = "ipAddress")]
    pub ip_address: String,
    #[serde(rename = "netmask")]
    pub netmask: String,
    #[serde(rename = "gateway")]
    pub gateway: String,
}

impl NetworkConfig {
    pub fn new(ip_address: String, netmask: String, gateway: String) -> NetworkConfig {
        NetworkConfig {
            ip_address,
            netmask,
            gateway,
        }
    }
}
