/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SystemState {
    #[serde(rename = "Unprovisioned")]
    Unprovisioned,
    #[serde(rename = "Locked")]
    Locked,
    #[serde(rename = "Operational")]
    Operational,
}

impl ToString for SystemState {
    fn to_string(&self) -> String {
        match self {
            Self::Unprovisioned => String::from("Unprovisioned"),
            Self::Locked => String::from("Locked"),
            Self::Operational => String::from("Operational"),
        }
    }
}

impl Default for SystemState {
    fn default() -> SystemState {
        Self::Unprovisioned
    }
}
