/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfo {
    #[serde(rename = "firmwareVersion")]
    pub firmware_version: String,
    #[serde(rename = "softwareVersion")]
    pub software_version: String,
    #[serde(rename = "hardwareVersion")]
    pub hardware_version: String,
    #[serde(rename = "buildTag")]
    pub build_tag: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "pcr")]
    pub pcr: String,
    #[serde(rename = "akPubP256")]
    pub ak_pub_p256: String,
    #[serde(rename = "akPubP384")]
    pub ak_pub_p384: String,
}

impl SystemInfo {
    pub fn new(
        firmware_version: String,
        software_version: String,
        hardware_version: String,
        build_tag: String,
        device_id: String,
        pcr: String,
        ak_pub_p256: String,
        ak_pub_p384: String,
    ) -> SystemInfo {
        SystemInfo {
            firmware_version,
            software_version,
            hardware_version,
            build_tag,
            device_id,
            pcr,
            ak_pub_p256,
            ak_pub_p384,
        }
    }
}
