/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TlsKeyGenerateRequestData {
    #[serde(rename = "type")]
    pub r#type: crate::models::TlsKeyType,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
}

impl TlsKeyGenerateRequestData {
    pub fn new(r#type: crate::models::TlsKeyType) -> TlsKeyGenerateRequestData {
        TlsKeyGenerateRequestData {
            r#type,
            length: None,
        }
    }
}


