/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// RandomData struct for RandomData
type RandomData struct {
	Random               string `json:"random"`
	AdditionalProperties map[string]interface{}
}

type _RandomData RandomData

// NewRandomData instantiates a new RandomData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRandomData(random string) *RandomData {
	this := RandomData{}
	this.Random = random
	return &this
}

// NewRandomDataWithDefaults instantiates a new RandomData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRandomDataWithDefaults() *RandomData {
	this := RandomData{}
	return &this
}

// GetRandom returns the Random field value
func (o *RandomData) GetRandom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Random
}

// GetRandomOk returns a tuple with the Random field value
// and a boolean to check if the value has been set.
func (o *RandomData) GetRandomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Random, true
}

// SetRandom sets field value
func (o *RandomData) SetRandom(v string) {
	o.Random = v
}

func (o RandomData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["random"] = o.Random
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *RandomData) UnmarshalJSON(bytes []byte) (err error) {
	varRandomData := _RandomData{}

	if err = json.Unmarshal(bytes, &varRandomData); err == nil {
		*o = RandomData(varRandomData)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "random")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRandomData struct {
	value *RandomData
	isSet bool
}

func (v NullableRandomData) Get() *RandomData {
	return v.value
}

func (v *NullableRandomData) Set(val *RandomData) {
	v.value = val
	v.isSet = true
}

func (v NullableRandomData) IsSet() bool {
	return v.isSet
}

func (v *NullableRandomData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRandomData(val *RandomData) *NullableRandomData {
	return &NullableRandomData{value: val, isSet: true}
}

func (v NullableRandomData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRandomData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
