/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// SystemState the model 'SystemState'
type SystemState string

// List of SystemState
const (
	SYSTEMSTATE_UNPROVISIONED SystemState = "Unprovisioned"
	SYSTEMSTATE_LOCKED        SystemState = "Locked"
	SYSTEMSTATE_OPERATIONAL   SystemState = "Operational"
)

var allowedSystemStateEnumValues = []SystemState{
	"Unprovisioned",
	"Locked",
	"Operational",
}

func (v *SystemState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SystemState(value)
	for _, existing := range allowedSystemStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SystemState", value)
}

// NewSystemStateFromValue returns a pointer to a valid SystemState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSystemStateFromValue(v string) (*SystemState, error) {
	ev := SystemState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SystemState: valid values are %v", v, allowedSystemStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SystemState) IsValid() bool {
	for _, existing := range allowedSystemStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SystemState value
func (v SystemState) Ptr() *SystemState {
	return &v
}

type NullableSystemState struct {
	value *SystemState
	isSet bool
}

func (v NullableSystemState) Get() *SystemState {
	return v.value
}

func (v *NullableSystemState) Set(val *SystemState) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemState) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemState(val *SystemState) *NullableSystemState {
	return &NullableSystemState{value: val, isSet: true}
}

func (v NullableSystemState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
