/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// KeyType the model 'KeyType'
type KeyType string

// List of KeyType
const (
	KEYTYPE_RSA        KeyType = "RSA"
	KEYTYPE_CURVE25519 KeyType = "Curve25519"
	KEYTYPE_EC_P224    KeyType = "EC_P224"
	KEYTYPE_EC_P256    KeyType = "EC_P256"
	KEYTYPE_EC_P384    KeyType = "EC_P384"
	KEYTYPE_EC_P521    KeyType = "EC_P521"
)

var allowedKeyTypeEnumValues = []KeyType{
	"RSA",
	"Curve25519",
	"EC_P224",
	"EC_P256",
	"EC_P384",
	"EC_P521",
}

func (v *KeyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := KeyType(value)
	for _, existing := range allowedKeyTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid KeyType", value)
}

// NewKeyTypeFromValue returns a pointer to a valid KeyType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKeyTypeFromValue(v string) (*KeyType, error) {
	ev := KeyType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KeyType: valid values are %v", v, allowedKeyTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KeyType) IsValid() bool {
	for _, existing := range allowedKeyTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to KeyType value
func (v KeyType) Ptr() *KeyType {
	return &v
}

type NullableKeyType struct {
	value *KeyType
	isSet bool
}

func (v NullableKeyType) Get() *KeyType {
	return v.value
}

func (v *NullableKeyType) Set(val *KeyType) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyType) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyType(val *KeyType) *NullableKeyType {
	return &NullableKeyType{value: val, isSet: true}
}

func (v NullableKeyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
