/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PublicKey struct for PublicKey
type PublicKey struct {
	Mechanisms           []KeyMechanism `json:"mechanisms"`
	Type                 KeyType        `json:"type"`
	Key                  KeyPublicData  `json:"key"`
	Operations           int32          `json:"operations"`
	AdditionalProperties map[string]interface{}
}

type _PublicKey PublicKey

// NewPublicKey instantiates a new PublicKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicKey(mechanisms []KeyMechanism, type_ KeyType, key KeyPublicData, operations int32) *PublicKey {
	this := PublicKey{}
	this.Mechanisms = mechanisms
	this.Type = type_
	this.Key = key
	this.Operations = operations
	return &this
}

// NewPublicKeyWithDefaults instantiates a new PublicKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicKeyWithDefaults() *PublicKey {
	this := PublicKey{}
	return &this
}

// GetMechanisms returns the Mechanisms field value
func (o *PublicKey) GetMechanisms() []KeyMechanism {
	if o == nil {
		var ret []KeyMechanism
		return ret
	}

	return o.Mechanisms
}

// GetMechanismsOk returns a tuple with the Mechanisms field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetMechanismsOk() (*[]KeyMechanism, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mechanisms, true
}

// SetMechanisms sets field value
func (o *PublicKey) SetMechanisms(v []KeyMechanism) {
	o.Mechanisms = v
}

// GetType returns the Type field value
func (o *PublicKey) GetType() KeyType {
	if o == nil {
		var ret KeyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetTypeOk() (*KeyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PublicKey) SetType(v KeyType) {
	o.Type = v
}

// GetKey returns the Key field value
func (o *PublicKey) GetKey() KeyPublicData {
	if o == nil {
		var ret KeyPublicData
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetKeyOk() (*KeyPublicData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PublicKey) SetKey(v KeyPublicData) {
	o.Key = v
}

// GetOperations returns the Operations field value
func (o *PublicKey) GetOperations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *PublicKey) GetOperationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operations, true
}

// SetOperations sets field value
func (o *PublicKey) SetOperations(v int32) {
	o.Operations = v
}

func (o PublicKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mechanisms"] = o.Mechanisms
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PublicKey) UnmarshalJSON(bytes []byte) (err error) {
	varPublicKey := _PublicKey{}

	if err = json.Unmarshal(bytes, &varPublicKey); err == nil {
		*o = PublicKey(varPublicKey)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "mechanisms")
		delete(additionalProperties, "type")
		delete(additionalProperties, "key")
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePublicKey struct {
	value *PublicKey
	isSet bool
}

func (v NullablePublicKey) Get() *PublicKey {
	return v.value
}

func (v *NullablePublicKey) Set(val *PublicKey) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKey) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKey(val *PublicKey) *NullablePublicKey {
	return &NullablePublicKey{value: val, isSet: true}
}

func (v NullablePublicKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
