/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// KeyGenerateRequestData struct for KeyGenerateRequestData
type KeyGenerateRequestData struct {
	Mechanisms []KeyMechanism `json:"mechanisms"`
	Algorithm KeyAlgorithm `json:"algorithm"`
	Length *int32 `json:"length,omitempty"`
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KeyGenerateRequestData KeyGenerateRequestData

// NewKeyGenerateRequestData instantiates a new KeyGenerateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyGenerateRequestData(mechanisms []KeyMechanism, algorithm KeyAlgorithm, ) *KeyGenerateRequestData {
	this := KeyGenerateRequestData{}
	this.Mechanisms = mechanisms
	this.Algorithm = algorithm
	return &this
}

// NewKeyGenerateRequestDataWithDefaults instantiates a new KeyGenerateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyGenerateRequestDataWithDefaults() *KeyGenerateRequestData {
	this := KeyGenerateRequestData{}
	return &this
}

// GetMechanisms returns the Mechanisms field value
func (o *KeyGenerateRequestData) GetMechanisms() []KeyMechanism {
	if o == nil  {
		var ret []KeyMechanism
		return ret
	}

	return o.Mechanisms
}

// GetMechanismsOk returns a tuple with the Mechanisms field value
// and a boolean to check if the value has been set.
func (o *KeyGenerateRequestData) GetMechanismsOk() (*[]KeyMechanism, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Mechanisms, true
}

// SetMechanisms sets field value
func (o *KeyGenerateRequestData) SetMechanisms(v []KeyMechanism) {
	o.Mechanisms = v
}

// GetAlgorithm returns the Algorithm field value
func (o *KeyGenerateRequestData) GetAlgorithm() KeyAlgorithm {
	if o == nil  {
		var ret KeyAlgorithm
		return ret
	}

	return o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value
// and a boolean to check if the value has been set.
func (o *KeyGenerateRequestData) GetAlgorithmOk() (*KeyAlgorithm, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Algorithm, true
}

// SetAlgorithm sets field value
func (o *KeyGenerateRequestData) SetAlgorithm(v KeyAlgorithm) {
	o.Algorithm = v
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *KeyGenerateRequestData) GetLength() int32 {
	if o == nil || o.Length == nil {
		var ret int32
		return ret
	}
	return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyGenerateRequestData) GetLengthOk() (*int32, bool) {
	if o == nil || o.Length == nil {
		return nil, false
	}
	return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *KeyGenerateRequestData) HasLength() bool {
	if o != nil && o.Length != nil {
		return true
	}

	return false
}

// SetLength gets a reference to the given int32 and assigns it to the Length field.
func (o *KeyGenerateRequestData) SetLength(v int32) {
	o.Length = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KeyGenerateRequestData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyGenerateRequestData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KeyGenerateRequestData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *KeyGenerateRequestData) SetId(v string) {
	o.Id = &v
}

func (o KeyGenerateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mechanisms"] = o.Mechanisms
	}
	if true {
		toSerialize["algorithm"] = o.Algorithm
	}
	if o.Length != nil {
		toSerialize["length"] = o.Length
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *KeyGenerateRequestData) UnmarshalJSON(bytes []byte) (err error) {
	varKeyGenerateRequestData := _KeyGenerateRequestData{}

	if err = json.Unmarshal(bytes, &varKeyGenerateRequestData); err == nil {
		*o = KeyGenerateRequestData(varKeyGenerateRequestData)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "mechanisms")
		delete(additionalProperties, "algorithm")
		delete(additionalProperties, "length")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKeyGenerateRequestData struct {
	value *KeyGenerateRequestData
	isSet bool
}

func (v NullableKeyGenerateRequestData) Get() *KeyGenerateRequestData {
	return v.value
}

func (v *NullableKeyGenerateRequestData) Set(val *KeyGenerateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyGenerateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyGenerateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyGenerateRequestData(val *KeyGenerateRequestData) *NullableKeyGenerateRequestData {
	return &NullableKeyGenerateRequestData{value: val, isSet: true}
}

func (v NullableKeyGenerateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyGenerateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


